# Site settings
title: 且听风吟
SEOTitle: Distiny的博客 | 且听风吟
header-img: img/post-bg-desk.jpg
email: 244258787@qq.com
description: "Actions speak louder than words."
keyword: "Distiny, 且听风吟"
url: "https://distiny-cool.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/distiny-cool/distiny-cool.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Actions speak louder than words."
sidebar-avatar: /img/about-distiny-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     xxxxxxx
zhihu_username:     distiny-cool
github_username:    distiny-cool
# facebook_username:  xxxxxxx
# jianshu_username:   xxxxxxx
twitter_username:   DistinyKody




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: distiny_cool

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 95e38a49d259269322c6                            #生成的clientID
  clientSecret: afb21acbf35f14fa8ec740faf3c4772bdb6b5edd     #生成的clientSecret
  repo: distiny-cool.github.io    #仓库名称
  owner: distiny-cool    #github用户名
  admin: distiny-cool
  distractionFreeMode: flase #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 6972be46064fb0759d38331ac89da1d8

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 2              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# # Friends
# friends: [
#     {
#         title: "简书·BY",
#         href: "http://www.jianshu.com/u/e71990ada2fd"
#     },{
#         title: "Apple",
#         href: "https://apple.com"
#     },{
#         title: "Apple Developer",
#         href: "https://developer.apple.com/"
#     }
# ]
